### ISSUE TITLE
Rebinding keybinds.

### ISSUE THREAD

**Issue by ElectroBytezLV** [JU5TDIE/Lester-Ver2.0#1]
Hello. I'd like you to provide us with some documentation regarding on how to change the default keybinds, or you could implement a system, which allows you to change the keybinds from the .exe file. I'd like to change the keybinds to CTRL+F5 for example, instead of just F5 on all of the hacks. For example, on AHK the CTRL button is also known as "^", so I'm not sure which ones are here, on Python. I do know how to access the source code and such, of course, but as I mentioned above, don't know the correct keybinds.

**Comment by JU5TDIE** [comment]
Thank you for the issue!

I will add .ini or .json file, which is for key binds and other settings. And the format of CTRL+F5 in pynput is <ctrl>+<F5>; just put '<' and '>' on the first and last place of key.

**Comment by ElectroBytezLV** [comment]
> Thank you for the issue!
> 
> I will add `.ini` or `.json` file, which is for key binds and other settings. And the format of `CTRL+F5` in pynput is `<ctrl>+<F5>`; just put < and > on the first and last place of key.

So if I wanted to change the activation hotkey in the "main.py" file, it should look like this:
```
	elif k == "<ctrl>+<F5>":
		thread = Thread(target = casinofingerprint.main)
		thread.start()

	elif k == "<ctrl>+<F6>":
		thread = Thread(target = casinokeypad.main)
		thread.start()

	elif k == "<ctrl>+<F7>":
		thread = Thread(target = cayofingerprint.main)
		thread.start()

	elif k == "<ctrl>+<F8>":
		thread = Thread(target = cayovoltage.main)
		thread.start()
```

**Comment by JU5TDIE** [comment]
Check the new script, i just fixed it yesterday
