### ISSUE TITLE
Keybind for restarting the script.

### ISSUE THREAD

**Issue by ElectroBytezLV** [JU5TDIE/Lester-Ver2.0#2]
I think there should be a keybind to restart the script, in case you mess up.

**Comment by JU5TDIE** [comment]
Thank you for the issue!

I'll add it on the next update

**Comment by ElectroBytezLV** [comment]
Well, lets say you accidentally click one of the hotkeys too quickly on one of the hacks and it doesn't do it right. (just try to click F7 quicker before all the prints properly show up). So in that case I'm pretty sure you'd have to reopen the script manually. A hotkey, which would restart it automatically would solve this problem and properly do the print even if it failed the first time.

**Comment by JU5TDIE** [comment]
If that's the case, you don't have to reopen the script. Unselect the selected puzzles and retry it.
