### ISSUE TITLE
Unreliable keypad cracker script.

### ISSUE THREAD

**Issue by ElectroBytezLV** [JU5TDIE/Lester-Ver2.0#3]
The keypad cracker script is kinda unreliable and requires precise input and attention for it to work. I think it should be remade to be more reliable and work without you having to press F6 on the last blue circle pattern, in case you miss it.

**Comment by JU5TDIE** [comment]
Thank you for the issue!

Yeah.. it is unreliable but that's how it works. Do you have any idea of it?

**Comment by ElectroBytezLV** [comment]
Well, unreliable wouldnt be the right word maybe. It just require a lot of precision and timing, which sometimes is really hard and you can miss it. Maybe there is a way to make some kind of automatic detection, which would automatically record the circles and start the process right away or after clicking a hotkey. Maybe they would be temporarily stored in a cache folder in the script folder or something, not sure, that would have to be figured out by you.

**Comment by JU5TDIE** [comment]
I actually tried that method before, but that makes it more complex. If the current one is too uncomfortable, I can add the option to choose the method.

**Comment by ElectroBytezLV** [comment]
> I actually tried that method before, but that makes it more complex. If the current one is too uncomfortable, I can add the option to choose the method.

Well imo the keypad cracker is the most unuseful from them all, since if you do the level 2 security passes prep (which is really easy and quick, isn't much harder from the level 1 pass), then you don't even need it. But in the change that you miss the 6th blink, you cant tell the script to do the puzzle, since you missed it, that's what I mean. I'm just trying to improve the cracker, when in reality I don't even need it, in fact I've never done this puzzle before.
