### ISSUE TITLE
Stuck on "Searching Grand Theft Auto V..."

### ISSUE THREAD

**Issue by steve-1507** [JU5TDIE/Lester-Ver2.0#4]
What does the program do at this point? Is it looking for any game files? If it is, maybe it broke because I installed GTA5 through Steam on my F: partition. Can you provide some help please?

**Comment by JU5TDIE** [comment]
No, it's actually looking for the program that has "Grand Theft Auto V" title every second. You can actually bypass this step by running other program that has "Grand Theft Auto V" title but it would be annoying to do this every time. Is your gta 5 modded by any chance or does it have a different title?

**Comment by JU5TDIE** [comment]
@steve-1507 I'll close this issue in three days, it would be appreciated if you could tell me if you still have this issue or not

**Comment by steve-1507** [comment]
So you need to have GTA 5 open for this to work?

**Comment by JU5TDIE** [comment]
> So you need to have GTA 5 open for this to work?

Yes
