### ISSUE TITLE
i cant install for some reason requirements

### ISSUE THREAD

**Issue by Standa-kkt** [JU5TDIE/Lester-Ver2.0#6]
![image](https://github.com/user-attachments/assets/54fdb08f-6381-45b5-bde1-ac0e7e2d5338)
here is the error its giving me, transtation: system cant find file/folder
thanks for your help/time

**Comment by JU5TDIE** [comment]
It's the problem with path. Try using this command instead `python -m pip install` Also python 3.8 is the recommended version for this repository.
